apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: card-game
  template:
    metadata:
      labels:
        app: card-game
    spec:
      containers:
      - name: card-game
        image: asia-northeast3-docker.pkg.dev/hyukyee-7777/card-game-repo/card-game:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
